#define AR_AYUDA "help-es.txt"
#define AR_BIENVENIDA "hello-es.txt"
#define MSJ_BIENVENIDA "Bievenido a Simpletron"
#define MSJ_INGRESE_POS "Ingrese la palabra a guardar en la posicion de memoria"
/*Mensajes en ESPAÑOL para el seguimiento del procedimiento*/
#define MSJ_COMIENZO_PROC "*** INICIO EJECUCION DEL SIMPLETRON ***"
#define MSJ_LEER "Se ha guardado la palabra"
#define MSJ_POS "En la posicion de memoria"
#define MSJ_STOUT "se encuentra el valor"
#define MSJ_CARGA "Se cargo en el acumulador la palabra de la posicion de memoria"
#define MSJ_GUARDAR "Se guardo el valor del acumulador a la posicion de memoria"
#define MSJ_SUMA "Se le ha sumado al acumulador la palabra de la posicion de memoria"
#define MSJ_RESTA "Se le ha restado al acumulador la palabra de la posicion de memoria"
#define MSJ_DIV "Se ha dividido el valor del acumulador por la palabra de la posicion de memoria"
#define MSJ_MULT "Se ha multiplicado el valor del acumulador por la palabra de la posicion de memoria"
#define MSJ_JMP "Se ha saltado a la orden en la posicion de memoria"
#define MSJ_CARGARP "Se ha cargado al acumulador el valor de lo apuntado por el puntero de la posicion"
#define MSJ_GUARDARP "Se ha guardado el valor del acumulador en la posicion indicada por el puntero de la posicion"
#define MSJ_FIN_DEL_PROGRAMA "*** FIN DE EJECUCION DEL SIMPLETRON ***"
/*Mensajes en ESPAÑOL para impresion de datos*/
#define MSJ_REGISTRO "REGISTROS:"
#define MSJ_ACUMULADOR "Acumulador:"
#define MSJ_OPCODE "Op Code:"
#define MSJ_OPERANDO "Operando:"
#define MSJ_PCOUNT "Program Counter:"
#define MSJ_INSTRUCCION "Instruccion:"
#define MSJ_MEMORIA "Memoria:"

#define MSJ_AR_ENTRADA "Archivo de entrada"
#define MSJ_AR_SALIDA "Archivo de salida"
#define MSJ_CANT_PROC "Cantidad de procesos"
#define MSJ_NO_IN "No hay archivo de entrada"
#define MSJ_NO_OUT "No hay archivo de salida"
#define MSJ_NOM_AR "Nombre de archivo"
/*Mensajes en ESPAÑOL para las diferentes funciones*/
/*Mensajes para la funcion grabar_fichero_txt en ESPAÑOL*/
#define MSJ_AR_GUARDADO "Nombre del archivo guardado"