#define AR_AYUDA "help-us.txt"
#define AR_BIENVENIDA "hello-es.txt"
#define MSJ_BIENVENIDA "Welcome to Simpletron"
#define MSJ_INGRESE_POS "Enter the word to be saved on the following memory position"
/*Mensajes en INGLES para el seguimiento del procedimiento*/
#define MSJ_COMIENZO_PROC "*** SIMPLETRONS EXECUTION STARTED ***"
#define MSJ_LEER "The word has been saved"
#define MSJ_POS "at memory position"
#define MSJ_STOUT "there is the value"
#define MSJ_CARGA "It has been saved into the accumulator the word from the following memory position"
#define MSJ_GUARDAR "The accumulators value has been saved into the following memory position"
#define MSJ_SUMA "It has been added to the accumulators value the word from the following memory position"
#define MSJ_RESTA "It has been substracted to the accumulator value the word from the following memory position"
#define MSJ_DIV "The accumulators value has been divided by the word from the following memory position"
#define MSJ_MULT "The accumulators value has been multiplied by the word from the following memory position"
#define MSJ_JMP "Jumpled to the order in the following memory position"
#define MSJ_CARGARP "It has been saved into the accumulator the value pointed by the pointer in the following memory position"
#define MSJ_GUARDARP "The accumulators value has been saved into the pointed memory slot by the pointer in the following position"
#define MSJ_FIN_DEL_PROGRAMA "*** SIMPLETRONS EXECUTINO ENDED **+"
/*Mensajes en INGLES para impresion de datos*/
#define MSJ_REGISTRO "REGISTRY:"
#define MSJ_ACUMULADOR "Accumulator:"
#define MSJ_OPCODE "Op Code:"
#define MSJ_OPERANDO "Operand:"
#define MSJ_PCOUNT "Program Counter:"
#define MSJ_INSTRUCCION "Instruction:"
#define MSJ_MEMORIA "Memory:"

#define MSJ_AR_ENTRADA "Entry file"
#define MSJ_AR_SALIDA "Output file"
#define MSJ_CANT_PROC "Number of processes"
#define MSJ_NO_IN "No entry file"
#define MSJ_NO_OUT "No output file"
#define MSJ_NOM_AR "File name"
/*Mensajes en INGLES para las diferentes funciones*/
/*Mensajes para la funcion grabar_fichero_txt en INGLES*/
#define MSJ_AR_GUARDADO "Name of the saved file"